services:
  mysql_babel:
    image: mysql:8.0
    container_name: mysql_babel
    environment:
      MYSQL_ROOT_PASSWORD: "test123.*babel"
      MYSQL_DATABASE: PRUEBA_BABEL
      MYSQL_USER: root
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  nodejs_babel:
    build: ./nodejs_babel
    networks:
      - my-network
    depends_on:
      - mysql_babel
    ports:
      - "3010:3000"
    environment:
      - DB_HOST=mysql_babel
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=test123.*babel
      - DB_NAME=PRUEBA_BABEL

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
