-- Grant privileges
GRANT ALL PRIVILEGES ON RESTAURANT_ALEGRO.* TO 'user'@'%';
FLUSH PRIVILEGES;


CREATE DATABASE PRUEBA_BABEL;

USE PRUEBA_BABEL;

CREATE TABLE PAISES(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50),
    PRIMARY KEY(id)
);





CREATE TABLE CIUDADES(
    id INT NOT NULL AUTO_INCREMENT,
    detailName VARCHAR(50),
    masterId INT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (masterId) REFERENCES PAISES(id)
    
)